### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by afranoys** [BrianBGrant/DNDCv.CAN#1]
Hello,

I have a question: how can I find the results? For the 'normal' DNDC 9.5 there is a map with result/record/site. I can't find the result files after running the model... 
Thank you very much for sharing this improved DNDC model!

Kind regards,
Astrid

**Comment by BrianBGrant** [comment]
Hi Astrid,

I'm assuming you found this off Github? Let me assemble a full package for
you to download as it's been a short while since I last updated GitHub.

Normally the results should be written to DNDC/Results/Record/Site if
you're running a site run and DNDC/Results/Record/Batch if you're running
the model in batch mode.

I have some user documentation as well that I can send that gives some more
explanation of the DNDC changes.

Cheers,

Brian

**Comment by afranoys** [comment]
Hi Brian,

Yes, I found the download link (to github) through the following article: 'Development of the DNDC model to improve soil hydrology and incorporate mechanistic tile drainage: A comparative analysis with RZWQM2.'

A full package and user documentation would be very much appreciated! Thank you.

Astrid

**Comment by BrianBGrant** [comment]
Hi Astrid,

Sorry for the delay but I was reworking some calculations I wanted to
include in the release I sent you.

You can download the model from my google drive.

*Google Drive link*

https://drive.google.com/drive/folders/1nHdmQewPAicf2Iyqy3uSDmKkIdkoXkQX?usp=sharing


*Just unzip to C:\DNDC*

If you want to run from D: drive you can but you'll need to modify the
example simulations to point to D: instead of C:

Let me know if you run into any issues.

Cheers,

Brian

**Comment by afranoys** [comment]
Hi Brian,

Thank you for this download! However, I ran it (so I could see the results in the GUI), but I can not find the (detailed) results in my files.. 

Thank you a lot for your help.

Kind regards,
Astrid

**Comment by BrianBGrant** [comment]
Hi Anita,

You should have results written out to

C:\DNDC\Result\Record\Site

if it is installed on the C: root drive for an individual site run.

Try looking for the file *multi_year_summary.csv* on your computer and it
should show you where DNDC is writing out your output directory to.

Cheers,

Brian

**Comment by afranoys** [comment]
Hi Brian,

The issue is that I just don't have a results map in the DNDC file... 
![image](https://user-images.githubusercontent.com/74614945/99688764-78774a00-2a86-11eb-80c7-2a8076b5d02f.png)

If i make the maps manually the result doesn't appear in there. Also no summary file exists after running the model.. 

Thank you a lot!

Kind regards,
Astrid

**Comment by BrianBGrant** [comment]
Hi Astrid,

Sorry, but this is still an old legacy coding problem but the model needs
to be always run from a root *DNDC* directory to write the results out
properly.
To fix your issue
1. Please rename your other DNDC directory to something else
2.  and rename DNDC-update (vCan) to C:\DNDC

This will help fix the problem.

Cheers,

Brian

**Comment by afranoys** [comment]
Hi Brian,

It works! Thank you

Kind regards,
Astrid

**Comment by BrianBGrant** [comment]
Glad to hear it. If you have any specific questions or encounter bugs
please let me know. We're constantly developing and fixing issues.


Cheers,

Brian
