### ISSUE TITLE
request for resolving the app crash issue

### ISSUE THREAD

**Issue by manipes** [BrianBGrant/DNDCv.CAN#4]
Hi Brian,

Thank you for sharing the modified DNDC exe version. I was looking for a way to change the grain filling parameter and it's great to see that your latest version is having that feature. For my case, I am more interested in running the multi-year simulation for palm tree. I was running the 14 year simulation and when I try to increase Thermal degree days (TDD) to more than 19000, the app is crashing with a message 

"Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	DNDC95.exe
  Application Version:	1.0.0.1
  Application Timestamp:	6058e715
  Fault Module Name:	DNDCgo.dll
  Fault Module Version:	1.0.0.1
  Fault Module Timestamp:	6058e712
  Exception Code:	80000003
  Exception Offset:	000ad52e
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	9d53
  Additional Information 4:	9d539ab2d38cfad867f683ba4be72a2d"

Attaching few screenshot of the setup. 
<img width="838" alt="Define farming management practices for total simulated years" src="https://user-images.githubusercontent.com/56326518/138241315-41de4fde-79fc-41ea-8bc4-cf3fe0bdd97f.png">
<img width="813" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/56326518/138241343-5baddeab-3de8-483b-a502-c104e461b41d.png">

The same setup was running in the original DNDC from University of New Hampshire. Would you please give me some pointers for resolving this issue.

thanks
Manikandan
.

**Comment by BrianBGrant** [comment]
Hi, Manikandan,

Can you send me your model dnd file. I can see if I can identify the
problem. Looks like the model file is populated with incorrect information.

Brian

**Comment by manipes** [comment]
Hi Brian,

Thank you very much for your response. I have shared the dnd file and sample climate file in the google drive (https://drive.google.com/drive/folders/1frhIxhmkI_gl28hB3wWVkZTyMG3SwJo8) for your perusal.

Thanks again for your time. 

Best,
Manikandan

**Comment by manipes** [comment]
> Hi Brian,
> 
> Thank you very much for your response. I have shared the dnd file and sample climate file in the google drive (https://drive.google.com/drive/folders/1frhIxhmkI_gl28hB3wWVkZTyMG3SwJo8) for your perusal.
> 
> Thanks again for your time.
> 
> Best, Manikandan

Hi Brian, 

I have shared the dnd file in google drive. Please have a look when you get a chance. 

Thanks for your time.

Best,
Manikandan

**Comment by BrianBGrant** [comment]
Hi Manikandan,

Sorry about the delay. I've been delayed because of some high-priority
project deliverables. I hope to look at your issue this evening or tomorrow
morning.

Cheers,

Brian

**Comment by manipes** [comment]
Hi Brian,

No worries. I understand. Please take your time. Thanks for your note.

Best,
Manikandan

**Comment by BrianBGrant** [comment]
Hi Manikandan,

I've looked at your files and while there were a few issues with the
parameterization there is also a internal issue with Palm that I need to
correct. I do need to understand the cropping system your intending to
simulate a bit better since I'm not that familiar with the region.

So it is a palm crop you intend to grow. What is the planned management of
the palm? Is there any? Or is this to represent a native growth over the 14
years.

Once I better understand that I'll be better able to help.

Cheers,


Brian

**Comment by manipes** [comment]
Hi Brian,

Thanks for looking into the shared files. I am trying to model the native growth of palm for 14 years. It was planted in 2007 and wanted to see the emission from palm fields till 2020. The lifecycle of the palm will be around 25 years. 

Please let me know if any clarification are required.

thanks
Manikandan

**Comment by BrianBGrant** [comment]
Hi Manipes,

Thanks for the background and the investigation of DNDC for palm growth.
I'm providing a new link to your model input files so that it works better
with DNDC (check the pathname directories in my file to ensure it's
pointing to the proper climate location). I'm also providing a new
executable for you to utilize for this work. I'll say the caveat of your
investigation is that I have little experience with DNDC in looking at
perennial tree/palm growth so I have no good idea about the magnitude of
growth you should be expecting.

Just a bit of information on why the crash. The model doesn't behave well
with TDD values set at values greater than 5000. Your interest in
simulating palm has identified a limitation in my framework that I'm going
to work to address. I'll move to remove this limitation in the future.

In the meantime here are the files and executables you can utilize to
simulate your situation. You might want to think about using a
heterogeneous soil profile to better quantify soil C concentration across
the 2m depths.

https://drive.google.com/drive/folders/1DPwzOeguHmDkElNgGiOc7LP2ftNxKrbO?usp=sharing



Cheers,

Brian

**Comment by manipes** [comment]
Hi Brian,

Thank you very much for taking time to look into my queries. I really appreciate it for correcting the input files and sharing the latest executable files. Thanks again for the sharing the details about the reason for the app crash (I was using very high value to simulate for 14 years, given 6500-7000 TDD per year/palm) and look forward to your release with flexible TDD. 

I have few queries and if you can give some pointers, it will be highly helpful.
1. I was using the land use as "upland crop field" instead of "woodland" as you suggested in the input files. With woodland setting, I observed that the grains are not coming in the second year onwards. I was trying to simulate the palm growth for 14 years by setting cropping system lifecycle as 14 years and setting the cropping parameters only for the first year (as in case of sugarcane). Just wondering whether the same settings will work for the woodland land use settings too.
2. Would you please share some documentation or any reference if you aware of on using DNDC for perennial crops/ tree using woodland land use setting.
3. Was also trying to understand your code base. Would be highly helpful if you can share any kind of documentation/papers to understand the code and the implementation.

thanks
Manikandan

**Comment by manipes** [comment]
Hi Brian,

Apologies for bothering you again with multiple queries. Thanks again for your support. Would highly appreciate any pointers on using the "woodland" option. With woodland settings for multiyear simulation, the grains are coming only for the first year and in subsequent years its giving zero grains although the emission number are there.

thanks
Manikandan

**Comment by BrianBGrant** [comment]
Hi Manikandan,

Sorry about the delays in response. We're kind of overloaded with work atm.

1) I wouldn't be able to suggest much with the woodland option currently. I
know this was a feature developed by Changsheng Li but I've not explored it
much. I have little experience in the code or in practice knowing the
implications of using this feature. I probably would avoid using it if your
noticing issues with biomass production.

2) The documentation I do have pertains to DNDCvCan. There is a bit of
guidance on perennials but not  much.

3) The documentation for code framework development is not very extensive.
I've been working on trying to improve it but it takes a bit of time. Also
I've made some headway on an alternative method for the growth routines
that should alleviate the TDD issue but I've not pushed it to github yet.
I'm hoping I can move it to the master branch sometime in the next couple
of months.

Good luck,

Brian

**Comment by manipes** [comment]
Hi Brian,

Thank you very much for the clarification. Will look forward to learn more about the alternative method for the growth routine. Thanks again for your continued support.

Best,
Manikandan
