### ISSUE TITLE
Request access to the source code

### ISSUE THREAD

**Issue by KatyushaScarlet** [BrianBGrant/DNDCv.CAN#7]
Hi Brian,

   We would like to know if we can get access to the source code of the DNDC model so that we can use it for academic research and to contribute to the agriculture in Taiwan.
    We are graduate students at National Tsing Hua University in Taiwan, and our lab has collaborated with many farms in Taiwan. We would like to build an improved DNDC model for Taiwan and make it available to farms in Taiwan.
    We also want to improve the DNDC model and make it can provide API for other automated programs (For example, ESP32 node with soil humidity sensors, gas sensors, etc.).
    We are using the DNDC model for academic research only, we are not a commercial organization and have no plans to commercialize it.
    If there is anything that we can do, our lab will cooperate fully and hope that we can work together.

Best regards,
Xiang Wang
High Speed Network Laboratory
National Tsing Hua University

**Comment by BrianBGrant** [comment]
Hi Xiang,

It's a bit of a challenge for us to share the source code freely as there are large portions of the DNDC v.CAN code that we are not the original authors of and Regrow (DNDC version 10) has some authority over. I would suggest you contact bill@regrow.ag (Dr. William Salas) to see if you can work with them for source code sharing. We can only share source code with formalized research partners that are not looking to commercialize the code for profit and whose research goals align with our efforts here at AAFC. I wish you good luck in your endeavors and please reach out if there are other issues we can assist with.

Best,

Brian

**Comment by Shruteejn** [comment]
Hi Brian,

I would like to know if I  can get access to the source code of the DNDC model so that I can use it for academic research and to contribute to the agriculture in INDIA. 
Im a 1 year phd scholar at IIT hyderabad in dept of climate change. I would like to build an improved DNDC model according to diff agroclimatic zones of INDIA. I will be using the DNDC model for academic research only, and have no plans to commercialize it.

Best regards,
Shrutee Jain
IIT Hyderabad
