### ISSUE TITLE
console exe not running

### ISSUE THREAD

**Issue by RamiALBASHA** [BrianBGrant/DNDCv.CAN#8]
Dear Brian,

The command line version of the model has a library-reading error ("Cannot open .\\Library\lib_soil\soil_8"). I have tried two possible solutions (copying the consol exe to the root directory of DNDC so that it could access all libraries, renaming "lib_soil" to "Lib_soil" in case the code is case-sensitive) but none worked. Would you have any idea why this error keeps occuring?

Context:
- OS Windows 11 Enterprise v. 22H2 on a x64 processor
- the syntaxe used is that indicated in "readme-Version-Prerelease9.5.6.txt" (not in "DNDCvCAN User Guide.pdf" P.20 which seems obsolete)

Thanks in advance for your help.

Rami

**Comment by BrianBGrant** [comment]
try running the command line version with  the additional switch "-root
[with the directory the DNDC95.exe resides in]"

For example -root C:\dndc\

The command line version expects the batchfile.txt you're running and the
executable to be located in the same directory.

See the following response below I provided to another user.

"

The issue is as follows.



   1. Normally I run the command line from the same root drive letter as
   where the model is located with the batch.txt nestled within the same model
   directory. I notice you’re running batch.txt outside of the model pathway
   (no worries since I never told you needed to nestle it within the model
   directory).  The issue is this causes is noted in the following point.
   2. It seems when the batch.txt is located outside the model directory
   the model source code for building the subdirectory pathways to the library
   files get confused as it starts (in your case) looking for the library
   files of the model runs in C:\library\ instead of C:\dndc\library\ . The
   command line executable is expecting the batch.txt in the same directory as
   the model executable.



Possible fixes.



   1. Move Batch.txt into your model directory where the executable is
   being run from. In your case move batch.txt into C:\dndc\
   2. The alternative solution is that you can use the command line switch
   “-root c:\dndc\” to force the subdirectory structure to understand where
   your library files are located. (see my last command line entry for example
   below)

"
Best

Brian

**Comment by RamiALBASHA** [comment]
Thanks for your prompte answer.
The solution with the "-root" switch fixed the problem !

Best
